# Generated by Django 5.0.4 on 2024-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='rating',
        ),
        migrations.AddField(
            model_name='explanation',
            name='rate',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_file',
            field=models.BinaryField(default=b''),
        ),
    ]
